AppBundle\Entity\Pages:
    type: entity
    repositoryClass: PagesRepository
    table: pages
    indexes:
        group_id:
            columns:
                - group_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        seo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        body:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        languageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: language_id
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: updated_at
        groupId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: group_id
    lifecycleCallbacks: {  }
